language: cpp

jobs:
  include:
    - os: linux
      dist: focal
      env: TYPE=Debug

    - os: linux
      dist: focal
      env: TYPE=Release

    - os: linux
      arch: arm64
      dist: focal
      env: TYPE=Debug

    - os: linux
      arch: arm64
      dist: focal
      env: TYPE=Release

    - os: osx
      env: TYPE=Release

    - os: osx
      env: TYPE=Debug

before_install:
  - eval "${MATRIX_EVAL}"
  - wget https://raw.githubusercontent.com/emp-toolkit/emp-readme/master/scripts/install.py
  - python install.py -install


script:
  - while sleep 400; do echo "=====[ $SECONDS seconds ]====="; done &
  - cmake -DCMAKE_BUILD_TYPE=$TYPE -DENABLE_FLOAT=On .
  - make 
  - ./bin/prp
  - ./bin/prg
  - ./bin/mitccrh
  - ./run ./bin/garble
  - ./run ./bin/netio
  - ./bin/bit
  - ./bin/int
  - ./bin/float
  - ./bin/ecc
  - ./bin/f2k
